export interface GlossaryEntry {
  term: string;
  def: string;
  topic?: string;
}

export const glossary: GlossaryEntry[] = [
  { term: 'A*', def: 'Best-first graph search using f(n) = g(n) + h(n). Optimal under admissibility (tree) or consistency (graph).' },
  { term: 'AC-3', def: 'Mackworth\'s arc-consistency algorithm. Queue of arcs, REVISE removes unsupported values. O(c·d³).' },
  { term: 'Admissible heuristic', def: 'h(n) ≤ h*(n) for all n — never overestimates the true cost-to-goal.' },
  { term: 'Alpha-beta pruning', def: 'Minimax with α/β bounds. Prune subtrees that can\'t affect the root value. Best case O(b^{m/2}).' },
  { term: 'Arc consistency', def: 'For every value v in D_i and every binary constraint (X_i, X_j) there exists w in D_j with (v,w) consistent.' },
  { term: 'Backjumping', def: 'Non-chronological backtrack: jump to the most recent variable in the conflict set, not just one level up.' },
  { term: 'Backtracking search', def: 'DFS over assignments with consistency check. The CSP search workhorse.' },
  { term: 'BFS', def: 'Breadth-first search. FIFO frontier. Complete; optimal for uniform costs; O(b^d) time/space.' },
  { term: 'CDCL', def: 'Conflict-Driven Clause Learning: DPLL + implication graph + learnt clauses + non-chronological backjumping + VSIDS.' },
  { term: 'Channeling constraint', def: 'A constraint linking two viewpoints, e.g. x[i]=j ↔ d[j]=i. Combines their propagation strengths.' },
  { term: 'CNF', def: 'Conjunctive Normal Form — conjunction of clauses, each a disjunction of literals.' },
  { term: 'Consistent heuristic', def: 'h(n) ≤ c(n,a,n\') + h(n\') for every successor. Triangle inequality. Implies admissibility.' },
  { term: 'Constraint graph', def: 'For binary CSPs: nodes = variables, edges = constraints. Tree-structured CSPs are O(nd²).' },
  { term: 'Cutoff test', def: 'Replacement for terminal test in real-time game search — typically "depth ≥ D".' },
  { term: 'Cutset conditioning', def: 'Find variables S whose removal makes the constraint graph a tree; try all d^|S| assignments.' },
  { term: 'Decision level', def: 'In CDCL: depth of the decision stack at which a literal was assigned (decided or implied).' },
  { term: 'Definite clause', def: 'Horn clause with exactly one positive literal. Equivalent to p1 ∧ … ∧ pk ⇒ q.' },
  { term: 'Degree heuristic', def: 'Tie-break for MRV: pick the variable in the most constraints on remaining variables.' },
  { term: 'DFS', def: 'Depth-first search. LIFO stack. Not complete in infinite spaces. O(bm) space.' },
  { term: 'Dominance (heuristic)', def: 'h1 dominates h2 if h1(n) ≥ h2(n) everywhere (both admissible). Dominant heuristics expand ≤ as many nodes.' },
  { term: 'DPLL', def: 'Davis–Putnam–Logemann–Loveland: backtracking SAT with unit propagation and pure-literal elimination.' },
  { term: 'Entailment', def: 'α ⊨ β iff every model satisfying α also satisfies β. Equivalently, M(α) ⊆ M(β).' },
  { term: 'Essence', def: 'High-level constraint specification language with set/mset/sequence/relation/function/partition types.' },
  { term: 'Essence Prime (Essence\')', def: 'Lower-level subset Savile Row consumes. Only int, bool, matrix. Abstract types must be encoded by hand.' },
  { term: 'Evaluation function (Eval)', def: 'Estimate of utility at non-terminal game states. Linear weighted sums are typical.' },
  { term: 'Forward chaining', def: 'Horn-clause inference: start from facts, fire applicable rules, repeat. Linear in KB size.' },
  { term: 'Forward checking (FC)', def: 'After assigning X_i, prune neighbours\' domains of inconsistent values. Local one-step propagation.' },
  { term: 'GSAT', def: 'Greedy hill-climbing on full assignments, picking flips that maximise satisfied clauses. Predecessor to WALKSAT.' },
  { term: 'Horn clause', def: 'Disjunction of literals with at most one positive literal.' },
  { term: 'IDS', def: 'Iterative-deepening DFS. Combines BFS\'s optimality with DFS\'s O(bd) space. O(b^d) time.' },
  { term: 'Implication graph', def: 'CDCL\'s DAG: nodes are literal assignments, edges from antecedents to implied literals.' },
  { term: 'Implied constraint', def: 'A constraint logically entailed by the model — doesn\'t change solutions, added to improve propagation.' },
  { term: 'Lex-leader constraint', def: 'For symmetry group G: ∀σ∈G, X ≤_lex σ(X). Forces lex-least canonical solution.' },
  { term: 'LCV', def: 'Least Constraining Value — value-ordering heuristic. Pick the value that rules out the fewest options for neighbours.' },
  { term: 'MAC', def: 'Maintaining Arc Consistency: run AC-3 after every assignment. Stronger than FC.' },
  { term: 'MCTS', def: 'Monte-Carlo Tree Search: Selection (UCB1) / Expansion / Simulation / Backpropagation.' },
  { term: 'Minimax', def: 'Optimal play value for two-player zero-sum games: max over MAX\'s actions of min over MIN\'s.' },
  { term: 'Min-conflicts', def: 'Local search for CSPs: reassign conflicted variable to value minimising violations. Solves million-queens in ~50 moves.' },
  { term: 'MRV', def: 'Minimum Remaining Values — fail-first variable-ordering heuristic. Pick variable with smallest domain.' },
  { term: 'Pure literal', def: 'A literal whose variable appears with only one polarity in the unsimplified formula. Can be safely set true.' },
  { term: 'Resolution', def: 'Inference rule: from (A ∨ ℓ) and (B ∨ ¬ℓ) derive (A ∨ B). Refutation-complete for CNF.' },
  { term: 'Savile Row', def: 'Constraint compiler from Essence Prime to solver input (Minion, SAT, MiniZinc, SMT, MaxSAT). Authors: Nightingale & Miguel.' },
  { term: 'Symmetry breaking', def: 'Adding constraints to remove symmetric copies of solutions/dead-ends. Lex-leader, value precedence, dynamic methods.' },
  { term: 'Tseitin transformation', def: 'Linear-size equisatisfiable CNF encoding using auxiliary variables for sub-formulas.' },
  { term: 'UCB1', def: 'Upper-Confidence-Bound: W_i/N_i + C·√(ln N / N_i). Multi-armed-bandit selection rule used in MCTS (then called UCT).' },
  { term: 'UCS', def: 'Uniform-Cost Search. Priority queue on g(n). Optimal for non-negative costs. Equivalent to Dijkstra.' },
  { term: 'Unit propagation (BCP)', def: 'If a clause has all but one literal falsified, the remaining literal must be true. Foundation of DPLL/CDCL.' },
  { term: '1-UIP', def: 'In CDCL: the Unique Implication Point closest to the conflict. Used to derive the asserting learnt clause.' },
  { term: 'Viewpoint', def: 'A selection of variables and domains sufficient to characterise solutions. One problem has many possible viewpoints.' },
  { term: 'VSIDS', def: 'Variable State Independent Decaying Sum — CDCL decision heuristic. Bump on learnt-clause appearance; periodic decay.' },
  { term: 'WALKSAT', def: 'Local-search SAT solver: pick random unsatisfied clause; flip random or least-break-count variable. Incomplete.' },
  { term: 'Watched literals', def: 'CDCL implementation trick: each clause watches two non-false literals; only re-check when a watch becomes false.' },
];
